"""keel queue tables: the dead-letter table and the schedule ledger

Shipped with the template, and autogenerated against a real Postgres rather
than hand-written, for the same reason ``0001`` was: a migration typed from
memory diverges from the model in exactly the details nobody checks.

``FailedJob`` and ``ScheduleRun`` are Keel's, not this application's, but they
register on the same ``keel.database.Model.metadata`` — so ``app/migrations/env.py``
imports them and this migration creates them. Remove either the import or this
file and the *next* autogenerate proposes ``DROP TABLE`` on both, because two
tables in the database will match no model. Applying that diff deletes every
dead letter and the scheduler's exactly-once ledger, and it reads like cleanup
in review.

``keel_failed_jobs`` stores the whole encoded envelope, not a reconstruction of
it, so a job can be re-dispatched verbatim by hand.  ``keel_schedule_runs``
carries a unique ``(entry, due_at)``: that constraint, not the advisory lock, is
what makes a scheduled job run exactly once across a fleet.

Revision ID: 0002_queue_tables
Revises: 0001_initial
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_queue_tables"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create Keel's dead-letter table and its schedule ledger."""
    op.create_table(
        "keel_failed_jobs",
        sa.Column("job", sa.String(length=255), nullable=False),
        sa.Column("envelope_id", sa.String(length=64), nullable=False),
        sa.Column("queue", sa.String(length=255), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("exception", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=False),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "envelope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keel_failed_jobs")),
    )
    op.create_index(
        op.f("ix_keel_failed_jobs_envelope_id"), "keel_failed_jobs", ["envelope_id"], unique=False
    )
    op.create_index(
        op.f("ix_keel_failed_jobs_failed_at"), "keel_failed_jobs", ["failed_at"], unique=False
    )
    op.create_index(op.f("ix_keel_failed_jobs_job"), "keel_failed_jobs", ["job"], unique=False)
    op.create_table(
        "keel_schedule_runs",
        sa.Column("entry", sa.String(length=255), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keel_schedule_runs")),
        sa.UniqueConstraint("entry", "due_at", name=op.f("uq_keel_schedule_runs_entry")),
    )
    op.create_index(
        op.f("ix_keel_schedule_runs_due_at"), "keel_schedule_runs", ["due_at"], unique=False
    )


def downgrade() -> None:
    """Drop them again, in dependency order."""
    op.drop_index(op.f("ix_keel_schedule_runs_due_at"), table_name="keel_schedule_runs")
    op.drop_table("keel_schedule_runs")
    op.drop_index(op.f("ix_keel_failed_jobs_job"), table_name="keel_failed_jobs")
    op.drop_index(op.f("ix_keel_failed_jobs_failed_at"), table_name="keel_failed_jobs")
    op.drop_index(op.f("ix_keel_failed_jobs_envelope_id"), table_name="keel_failed_jobs")
    op.drop_table("keel_failed_jobs")
